services:
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #     - AUTH0_DOMAIN=${AUTH0_DOMAIN}
  #     - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
  #     - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
  #     - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
  #   depends_on:
  #     - mongodb
  #   restart: on-failure
  
  # =============================================================================
  # MongoDB Database - Com Dados Pr√©-carregados
  # =============================================================================
  mongodb:
    image: pet-control-mongodb:latest
    container_name: pet-control-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pet_control
      MONGO_APP_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: